id: d4184
model: D4184 (ドライバモジュール)
tag: GPIO
category: Nch パワーMOSFETモジュール
description: 上のFETを利用したモーター制御と同等の回路が組まれたモジュールです D4184 パワーMOSFETが用られています
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/D4184.jpg
productUrl: https://www.amazon.co.jp/dp/B084VNKLFL
examples:
  - platform: microbit-driver
    status: incubator
    upstreamRepository: chirimen-oh/chirimen-drivers
    upstreamPath: microbit-examples/GPIO3
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen-drivers/tree/master/microbit-examples/GPIO3
    circuitUrl: https://tutorial.chirimen.org/raspi/section1#section-9
    verified: false
  - platform: legacy-gc-gpio
    status: archive
    upstreamRepository: chirimen-oh/chirimen
    upstreamPath: gc/gpio/section-9
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen/tree/master/gc/gpio/section-9
    circuitUrl: https://tutorial.chirimen.org/raspi/section1#section-9
    verified: false
circuit: https://tutorial.chirimen.org/raspi/section1#section-9
datasheet: null
reference: null
packages: []
platform: microbit-driver
status: incubator
verified: false
