id: BH1750
model: BH1750
tag: I2C
category: 照度センサー
description: 照度センサー
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/BH1750.jpg
productUrl: https://www.amazon.co.jp/dp/B011IGZD7E
examples:
  - platform: pizero-esm
    status: primary
    upstreamRepository: chirimen-oh/chirimen.org
    upstreamPath: pizero/src/esm-examples/bh1750
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen.org/tree/master/pizero/src/esm-examples/bh1750
    circuitUrl: https://github.com/chirimen-oh/chirimen.org/blob/master/pizero/src/esm-examples/bh1750/schematic.png
    verified: false
  - platform: microbit-driver
    status: incubator
    upstreamRepository: chirimen-oh/chirimen-drivers
    upstreamPath: microbit-examples/I2C_BH1750
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen-drivers/tree/master/microbit-examples/I2C_BH1750
    circuitUrl: https://github.com/chirimen-oh/chirimen-drivers/blob/master/microbit-examples/I2C_BH1750/imgs/pinbit_bh1750.png
    verified: false
  - platform: legacy-gc-i2c
    status: archive
    upstreamRepository: chirimen-oh/chirimen
    upstreamPath: gc/i2c/i2c-BH1750
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen/tree/master/gc/i2c/i2c-BH1750
    circuitUrl: https://github.com/chirimen-oh/chirimen/blob/master/gc/i2c/i2c-BH1750/schematic.png
    verified: false
circuit: null
datasheet: null
reference: null
packages:
  - "@chirimen/bh1750"
platform: pizero-esm
status: primary
verified: false
