id: device-3
model: フレキシブルＬＥＤ　赤色
tag: GPIO
category: LED
description: 通電すると光る部品です(必ず抵抗を挟んで利用してください)
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/M-18006.jpg
productUrl: https://akizukidenshi.com/catalog/g/g118006/
examples:
  - platform: microbit-driver
    status: incubator
    upstreamRepository: chirimen-oh/chirimen-drivers
    upstreamPath: microbit-examples/GPIO1
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen-drivers/tree/master/microbit-examples/GPIO1
    circuitUrl: https://github.com/chirimen-oh/chirimen-drivers/blob/master/microbit-examples/GPIO1/imgs/pinbit_hello-real-world.png
    verified: false
  - platform: legacy-gc-i2c
    status: archive
    upstreamRepository: chirimen-oh/chirimen
    upstreamPath: gc/i2c/gpio-Blink
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen/tree/master/gc/i2c/gpio-Blink
    circuitUrl: https://github.com/chirimen-oh/chirimen/blob/master/gc/i2c/gpio-Blink/schematic.png
    verified: false
circuit: null
datasheet: null
reference: null
packages:
  - "@chirimen/hello-real-world"
platform: microbit-driver
status: incubator
verified: false
