id: l298n
model: L298N (ドライバモジュール)
tag: GPIO
category: DCモーター 正逆転コントローラ
description: STマイクロ社のフルブリッジドライバである L298N を使用したDCモーターコントローラです
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/L298N.jpg
productUrl: https://akizukidenshi.com/catalog/g/g106680/
examples:
  - platform: microbit-driver
    status: incubator
    upstreamRepository: chirimen-oh/chirimen-drivers
    upstreamPath: microbit-examples/GPIO_HBridge
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen-drivers/tree/master/microbit-examples/GPIO_HBridge
    circuitUrl: null
    verified: false
  - platform: legacy-gc-i2c
    status: archive
    upstreamRepository: chirimen-oh/chirimen
    upstreamPath: gc/i2c/gpio-HBridge
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen/tree/master/gc/i2c/gpio-HBridge
    circuitUrl: null
    verified: false
circuit: null
datasheet: null
reference: null
packages: []
platform: microbit-driver
status: incubator
verified: false
