id: MMA7660
model: MMA7660
tag: I2C
category: 3軸加速度センサ
description: 3軸の加速度を検出できるセンサです
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/placeholder.jpg
productUrl: https://chirimen.org/
examples:
  - platform: pizero-esm
    status: primary
    upstreamRepository: chirimen-oh/chirimen.org
    upstreamPath: pizero/src/esm-examples/mma7660
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen.org/tree/master/pizero/src/esm-examples/mma7660
    circuitUrl: https://github.com/chirimen-oh/chirimen.org/blob/master/pizero/src/esm-examples/mma7660/schematic.png
    verified: false
circuit: null
datasheet: null
reference: null
packages:
  - "@chirimen/mma7660"
platform: pizero-esm
status: primary
verified: false
