id: ISD1820
model: ISD1820
tag: GPIO
category: ボイスレコーダ
description: 内蔵マイクで録音した音声(最大10秒)を再生する基板です。GPIOで再生や録音のコントロールができます
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/ISD1820.jpg
productUrl: https://www.amazon.co.jp/s?k=ISD1820
examples:
  - platform: microbit-driver
    status: incubator
    upstreamRepository: chirimen-oh/chirimen-drivers
    upstreamPath: microbit-examples/GPIO1
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen-drivers/tree/master/microbit-examples/GPIO1
    circuitUrl: null
    verified: false
  - platform: legacy-gc-i2c
    status: archive
    upstreamRepository: chirimen-oh/chirimen
    upstreamPath: gc/i2c/gpio-Blink
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen/tree/master/gc/i2c/gpio-Blink
    circuitUrl: null
    verified: false
circuit: null
datasheet: null
reference: null
packages: []
platform: microbit-driver
status: incubator
verified: false
