id: neopixel-led-12x12
model: Neopixel LED 12x12
tag: I2C
category: フルカラーLED アレイ
description: 円形のパネルです
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/neopixel12.jpg
productUrl: https://chirimen.org/
examples:
  - platform: pizero-esm
    status: primary
    upstreamRepository: chirimen-oh/chirimen.org
    upstreamPath: pizero/src/esm-examples/neopixel-i2c
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen.org/tree/master/pizero/src/esm-examples/neopixel-i2c
    circuitUrl: https://github.com/chirimen-oh/chirimen.org/blob/master/pizero/src/esm-examples/neopixel-i2c/schematic.png
    verified: false
circuit: null
datasheet: null
reference: null
packages:
  - "@chirimen/neopixel-i2c"
platform: pizero-esm
status: primary
verified: false
