id: 2SK4017
model: 2SK4017
tag: GPIO
category: Nch パワーMOSFET
description: 直流電流の On/Off 制御を行う部品です
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/FET.jpg
productUrl: https://akizukidenshi.com/catalog/g/g107597/
examples:
  - platform: microbit-driver
    status: incubator
    upstreamRepository: chirimen-oh/chirimen-drivers
    upstreamPath: microbit-examples/GPIO3
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen-drivers/tree/master/microbit-examples/GPIO3
    circuitUrl: https://tutorial.chirimen.org/raspi/section1#section-9
    verified: false
  - platform: legacy-gc-gpio
    status: archive
    upstreamRepository: chirimen-oh/chirimen
    upstreamPath: gc/gpio/section-9
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen/tree/master/gc/gpio/section-9
    circuitUrl: https://tutorial.chirimen.org/raspi/section1#section-9
    verified: false
circuit: https://tutorial.chirimen.org/raspi/section1#section-9
datasheet: null
reference: null
packages: []
platform: microbit-driver
status: incubator
verified: false
