id: ADS1015
model: ADS1015
tag: I2C
category: ADC(アナログ電圧測定)
description: アナログ電圧を 12bit 精度のデジタル信号に変換する部品で、アナログセンサ等を利用する際に必要です
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/ADS1015.jpg
productUrl: https://www.switch-science.com/catalog/1136/
examples:
  - platform: legacy-gc-i2c
    status: archive
    upstreamRepository: chirimen-oh/chirimen
    upstreamPath: gc/i2c/i2c-ADS1015
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen/tree/master/gc/i2c/i2c-ADS1015
    circuitUrl: https://github.com/chirimen-oh/chirimen/blob/master/gc/i2c/i2c-ADS1015/schematic.png
    verified: false
circuit: https://github.com/adafruit/ADS1X15-Breakout-Board-PCBs
datasheet: https://cdn-shop.adafruit.com/datasheets/ads1015.pdf
reference: null
packages:
  - "@chirimen/ads1015"
platform: legacy-gc-i2c
status: archive
verified: false
