id: GP2Y0E03
model: GP2Y0E03
tag: I2C
category: 距離センサ
description: センサから対象物までの距離を測定できるセンサです( 50cm 程度まで)
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/gp2y0e03.jpg
productUrl: https://akizukidenshi.com/catalog/g/g107547/
examples:
  - platform: legacy-gc-i2c
    status: archive
    upstreamRepository: chirimen-oh/chirimen
    upstreamPath: gc/i2c/i2c-GP2Y0E03
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen/tree/master/gc/i2c/i2c-GP2Y0E03
    circuitUrl: null
    verified: false
circuit: null
datasheet: https://akizukidenshi.com/download/ds/sharp/gp2y0e03_e.pdf
reference: null
packages: []
platform: legacy-gc-i2c
status: archive
verified: false
