id: MG995
model: MG995
tag: Actuator
category: サーボモータ
description: Tower Pro 製のサーボモータです　メタルギヤが使われています　同一型番の互換品も多数流通（写真はその一例）
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/MG995.jpg
productUrl: https://www.amazon.co.jp/s?k=MG995&i=hobby
examples:
  - platform: legacy-gc-i2c
    status: archive
    upstreamRepository: chirimen-oh/chirimen
    upstreamPath: gc/i2c/i2c-PCA9685
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen/tree/master/gc/i2c/i2c-PCA9685
    circuitUrl: null
    verified: false
circuit: null
datasheet: https://www.towerpro.com.tw/product/mg995/
reference: null
packages: []
platform: legacy-gc-i2c
status: archive
verified: false
