id: 10k
model: 10kΩ
tag: GPIO
category: カーボン抵抗
description: 必要な場所に電気抵抗を入れる部品です(ここでは通常のものよりサイズが大きく、抵抗値が読みやすい商品を紹介しています)
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/register-2.jpg
productUrl: https://akizukidenshi.com/catalog/g/g107990/
examples:
  - platform: pizero-esm
    status: primary
    upstreamRepository: chirimen-oh/chirimen.org
    upstreamPath: pizero/src/esm-examples/hello-real-world
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen.org/tree/master/pizero/src/esm-examples/hello-real-world
    circuitUrl: null
    verified: false
  - platform: microbit-driver
    status: incubator
    upstreamRepository: chirimen-oh/chirimen-drivers
    upstreamPath: microbit-examples/GPIO1
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen-drivers/tree/master/microbit-examples/GPIO1
    circuitUrl: null
    verified: false
  - platform: legacy-gc-i2c
    status: archive
    upstreamRepository: chirimen-oh/chirimen
    upstreamPath: gc/i2c/gpio-Blink
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen/tree/master/gc/i2c/gpio-Blink
    circuitUrl: null
    verified: false
circuit: null
datasheet: null
reference: null
packages:
  - "@chirimen/hello-real-world"
platform: pizero-esm
status: primary
verified: false
