id: grove-light-tsl2561
model: Grove-Light (TSL2561)
tag: I2C
category: 光センサ
description: 0.1lx から 40000lx まで測定可能な照度センサです
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/Grove-Light.jpg
productUrl: https://www.switch-science.com/catalog/1174/
examples:
  - platform: legacy-gc-i2c
    status: archive
    upstreamRepository: chirimen-oh/chirimen
    upstreamPath: gc/i2c/i2c-Grove-Light
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen/tree/master/gc/i2c/i2c-Grove-Light
    circuitUrl: https://github.com/chirimen-oh/chirimen/blob/master/gc/i2c/i2c-Grove-Light/schematic.png
    verified: false
circuit: https://github.com/SeeedDocument/Grove-Digital_Light_Sensor/raw/master/res/Digital%20light%20sensor%20v1.0%20Sch.pdf
datasheet: https://raw.githubusercontent.com/SeeedDocument/Grove-Digital_Light_Sensor/master/res/TSL2561T.pdf
reference: https://wiki.seeedstudio.com/Grove-Digital_Light_Sensor/
packages:
  - "@chirimen/tsl2561"
platform: legacy-gc-i2c
status: archive
verified: false
