id: STHS34PF80
model: STHS34PF80
tag: I2C
category: 非接触温度センサ
description: 赤外線を利用して対象物の温度と周辺温度を測定できる非接触型温度センサーです。人感・動体検知機能も備えています
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/STHS34PF80.jpg
productUrl: https://www.switch-science.com/products/9321
examples:
  - platform: pizero-esm
    status: primary
    upstreamRepository: chirimen-oh/chirimen.org
    upstreamPath: pizero/src/esm-examples/sths34pf80
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen.org/tree/master/pizero/src/esm-examples/sths34pf80
    circuitUrl: https://github.com/chirimen-oh/chirimen.org/blob/master/pizero/src/esm-examples/sths34pf80/schematic.png
    driver: none
    verified: false
circuit: null
datasheet: https://www.st.com/resource/en/datasheet/sths34pf80.pdf
reference: https://www.st.com/en/mems-and-sensors/sths34pf80.html
packages:
  - "@chirimen/sths34pf80"
platform: pizero-esm
status: primary
verified: false
