id: 4pin
model: 4pin
tag: GPIO
category: タクトスイッチ
description: ボタンを押している間だけ電気を流す部品です(chirimen チュートリアルでは 2pin のものを採用しています)
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/tactSwitch.jpg
productUrl: https://akizukidenshi.com/catalog/g/g103647/
examples:
  - platform: pizero-esm
    status: primary
    upstreamRepository: chirimen-oh/chirimen.org
    upstreamPath: pizero/src/esm-examples/gpio-onchange
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen.org/tree/master/pizero/src/esm-examples/gpio-onchange
    circuitUrl: https://github.com/chirimen-oh/chirimen.org/blob/master/pizero/src/esm-examples/gpio-onchange/schematic.png
    verified: false
  - platform: microbit-driver
    status: incubator
    upstreamRepository: chirimen-oh/chirimen-drivers
    upstreamPath: microbit-examples/GPIO0
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen-drivers/tree/master/microbit-examples/GPIO0
    circuitUrl: https://github.com/chirimen-oh/chirimen-drivers/blob/master/microbit-examples/GPIO0/imgs/pinbit_gpio-onchange.png
    verified: false
  - platform: legacy-gc-i2c
    status: archive
    upstreamRepository: chirimen-oh/chirimen
    upstreamPath: gc/i2c/gpio-Button
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen/tree/master/gc/i2c/gpio-Button
    circuitUrl: https://github.com/chirimen-oh/chirimen/blob/master/gc/i2c/gpio-Button/schematic.png
    verified: false
circuit: null
datasheet: null
reference: null
packages:
  - "@chirimen/gpio-onchange"
platform: pizero-esm
status: primary
verified: false
