id: sht30-31
model: SHT30/31
tag: I2C
category: 温湿度複合センサ
description: 温度と湿度の両方が測定可能なセンサ
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/SHT30.jpg
productUrl: https://www.switch-science.com/catalog/6559/
examples:
  - platform: pizero-esm
    status: primary
    upstreamRepository: chirimen-oh/chirimen.org
    upstreamPath: pizero/src/esm-examples/sht30
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen.org/tree/master/pizero/src/esm-examples/sht30
    circuitUrl: null
    verified: false
  - platform: microbit-driver
    status: incubator
    upstreamRepository: chirimen-oh/chirimen-drivers
    upstreamPath: microbit-examples/I2C7_SHT30
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen-drivers/tree/master/microbit-examples/I2C7_SHT30
    circuitUrl: null
    verified: false
  - platform: legacy-gc-i2c
    status: archive
    upstreamRepository: chirimen-oh/chirimen
    upstreamPath: gc/i2c/i2c-SHT30
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen/tree/master/gc/i2c/i2c-SHT30
    circuitUrl: null
    verified: false
circuit: null
datasheet: https://sensirion.com/media/documents/213E6A3B/63A5A569/Datasheet_SHT3x_DIS.pdf
reference: null
packages:
  - "@chirimen/sht30"
platform: pizero-esm
status: primary
verified: false
