id: VL53L1X
model: VL53L1X
tag: I2C
category: 距離センサ
description: VL53L0Xより高出力長距離タイプ
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/VL53L1X.jpg
productUrl: https://www.switch-science.com/catalog/3938/
examples:
  - platform: pizero-esm
    status: primary
    upstreamRepository: chirimen-oh/chirimen.org
    upstreamPath: pizero/src/esm-examples/vl53l1x
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen.org/tree/master/pizero/src/esm-examples/vl53l1x
    circuitUrl: https://github.com/chirimen-oh/chirimen.org/blob/master/pizero/src/esm-examples/vl53l1x/schematic.png
    verified: false
  - platform: microbit-driver
    status: incubator
    upstreamRepository: chirimen-oh/chirimen-drivers
    upstreamPath: microbit-examples/I2C_VL53L1X
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen-drivers/tree/master/microbit-examples/I2C_VL53L1X
    circuitUrl: https://github.com/chirimen-oh/chirimen-drivers/blob/master/microbit-examples/I2C_VL53L1X/imgs/pinbit_vl53l1x.png
    verified: false
  - platform: legacy-gc-i2c
    status: archive
    upstreamRepository: chirimen-oh/chirimen
    upstreamPath: gc/i2c/i2c-VL53L1X
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen/tree/master/gc/i2c/i2c-VL53L1X
    circuitUrl: https://github.com/chirimen-oh/chirimen/blob/master/gc/i2c/i2c-VL53L1X/schematic.png
    verified: false
circuit: null
datasheet: null
reference: null
packages:
  - "@chirimen/vl53l1x"
platform: pizero-esm
status: primary
verified: false
