id: BMP180
model: BMP180
tag: I2C
category: 温度, 圧力 複合センサ
description: 温度と気圧の測定ができる複合センサです
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/BMP180.jpg
productUrl: http://www.aitendo.com/product/10760
examples:
  - platform: pizero-esm
    status: primary
    upstreamRepository: chirimen-oh/chirimen.org
    upstreamPath: pizero/src/esm-examples/bmp180
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen.org/tree/master/pizero/src/esm-examples/bmp180
    circuitUrl: https://github.com/chirimen-oh/chirimen.org/blob/master/pizero/src/esm-examples/bmp180/schematic.png
    verified: false
  - platform: microbit-driver
    status: incubator
    upstreamRepository: chirimen-oh/chirimen-drivers
    upstreamPath: microbit-examples/I2C_BMP180
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen-drivers/tree/master/microbit-examples/I2C_BMP180
    circuitUrl: https://github.com/chirimen-oh/chirimen-drivers/blob/master/microbit-examples/I2C_BMP180/imgs/pinbit_bmp180.png
    verified: false
  - platform: legacy-gc-i2c
    status: archive
    upstreamRepository: chirimen-oh/chirimen
    upstreamPath: gc/i2c/i2c-BMP180
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen/tree/master/gc/i2c/i2c-BMP180
    circuitUrl: https://github.com/chirimen-oh/chirimen/blob/master/gc/i2c/i2c-BMP180/schematic.png
    verified: false
circuit: null
datasheet: http://aitendo3.sakura.ne.jp/aitendo_data/product_img/sensor/BMP180/BMP180.pdf
reference: null
packages:
  - "@chirimen/bmp180"
platform: pizero-esm
status: primary
verified: false
