import type { MetaExample, MetaYamlContent, PlatformId } from "./types.js";

export const DRIVER_NONE = "none";

const CHIRIMEN_DRIVERS_PACKAGE_TREE =
  "https://github.com/chirimen-oh/chirimen-drivers/tree/master/packages";

export const JSDELIVR_NPM_PACKAGE_BASE = "https://www.jsdelivr.com/package/npm";

export const DEFAULT_CHIRIMEN_DRIVERS_README_URL =
  "https://raw.githubusercontent.com/chirimen-oh/chirimen-drivers/master/README.md";

const DOWNLOAD_START = "<!-- downloads-start -->";
const DOWNLOAD_STOP = "<!-- downloads-stop -->";
const PACKAGE_LINK_PATTERN = /\[(@chirimen\/[A-Za-z0-9._-]+)\]/g;

export function toKnownPackageSet(packages: string[]): Set<string> {
  return new Set(packages);
}

export function isKnownChirimenPackage(
  pkg: string,
  knownPackages: ReadonlySet<string>,
): boolean {
  return knownPackages.has(pkg);
}

export function jsdelivrPackageUrl(pkg: string): string {
  return `${JSDELIVR_NPM_PACKAGE_BASE}/${pkg}`;
}

export function resolveDriver(
  packages: string[],
  platform: PlatformId,
  knownPackages: ReadonlySet<string>,
): string {
  if (platform !== "pizero-esm") return DRIVER_NONE;

  const matched = packages.find((pkg) => knownPackages.has(pkg));
  if (!matched) return DRIVER_NONE;

  const slug = matched.replace(/^@chirimen\//, "");
  return `${CHIRIMEN_DRIVERS_PACKAGE_TREE}/${slug}`;
}

export function applyDriverToExamples(
  examples: MetaExample[],
  packages: string[],
  knownPackages: ReadonlySet<string>,
): MetaExample[] {
  return examples.map((example) => ({
    platform: example.platform,
    status: example.status,
    upstreamRepository: example.upstreamRepository,
    upstreamPath: example.upstreamPath,
    upstreamPathUrl: example.upstreamPathUrl,
    circuitUrl: example.circuitUrl,
    driver: resolveDriver(packages, example.platform, knownPackages),
    verified: example.verified,
  }));
}

export function applyDriverToMeta(
  meta: MetaYamlContent,
  knownPackages: ReadonlySet<string>,
): MetaYamlContent {
  return {
    ...meta,
    examples: applyDriverToExamples(meta.examples, meta.packages, knownPackages),
  };
}

export function sortChirimenPackages(packages: string[]): string[] {
  return [...packages].sort((a, b) => a.localeCompare(b));
}

export function parseDownloadPackages(markdown: string): string[] {
  const start = markdown.indexOf(DOWNLOAD_START);
  const stop = markdown.indexOf(DOWNLOAD_STOP);
  if (start === -1 || stop === -1 || stop <= start) {
    throw new Error(
      "chirimen-drivers README is missing downloads-start/stop markers",
    );
  }

  const section = markdown.slice(start, stop);
  const packages = [
    ...new Set(
      [...section.matchAll(PACKAGE_LINK_PATTERN)].map((match) => match[1]),
    ),
  ];
  if (packages.length === 0) {
    throw new Error(
      "chirimen-drivers Download section contains no @chirimen packages",
    );
  }

  return sortChirimenPackages(packages);
}

export function chirimenDriversPackagesDiffer(
  current: string[],
  remote: string[],
): boolean {
  const currentSorted = sortChirimenPackages(current);
  const remoteSorted = sortChirimenPackages(remote);
  if (currentSorted.length !== remoteSorted.length) return true;
  return currentSorted.some((pkg, index) => pkg !== remoteSorted[index]);
}

export function renderChirimenDriversYml(packages: string[]): string {
  const sorted = sortChirimenPackages(packages);
  const lines = [
    "# Snapshot of npm packages listed in the chirimen-drivers README Download section.",
    "# Used to decide jsDelivr README links and meta.yml examples[].driver URLs.",
    "# Source: https://github.com/chirimen-oh/chirimen-drivers/blob/master/README.md#download",
    "#",
    "# Regenerated by `pnpm sync:devices` when the Download section differs.",
    "",
    "packages:",
    ...sorted.map((pkg) => `  - ${JSON.stringify(pkg)}`),
    "",
  ];
  return lines.join("\n");
}
