id: ht16k33-14-led
model: HT16K33搭載 14セグメントLEDモジュール
tag: I2C
category: LED マトリックス
description: 上記と同等のコントローラが載った、14セグメントLEDのモジュールです。
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/HT16K33_14seg.jpg
productUrl: https://www.aitendo.com/product/20812
examples:
  - platform: pizero-esm
    status: primary
    upstreamRepository: chirimen-oh/chirimen.org
    upstreamPath: pizero/src/esm-examples/ht16k33
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen.org/tree/master/pizero/src/esm-examples/ht16k33
    circuitUrl: https://github.com/chirimen-oh/chirimen.org/blob/master/pizero/src/esm-examples/ht16k33/schematic.png
    verified: false
  - platform: legacy-gc-i2c
    status: archive
    upstreamRepository: chirimen-oh/chirimen
    upstreamPath: gc/i2c/i2c-HT16K33
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen/tree/master/gc/i2c/i2c-HT16K33
    circuitUrl: https://github.com/chirimen-oh/chirimen/blob/master/gc/i2c/i2c-HT16K33/schematic.png
    verified: false
circuit: null
datasheet: https://cdn-shop.adafruit.com/datasheets/ht16K33v110.pdf
reference: null
packages:
  - "@chirimen/ht16k33"
platform: pizero-esm
status: primary
verified: false
