id: TMP117
model: TMP117
tag: I2C
category: 温度センサ
description: -55℃ から +150℃ まで測定できる高精度温度センサです（精度±0.1℃）
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/tmp117.jpg
productUrl: https://www.switch-science.com/products/5963
examples:
  - platform: pizero-esm
    status: primary
    upstreamRepository: chirimen-oh/chirimen.org
    upstreamPath: pizero/src/esm-examples/tmp117
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen.org/tree/master/pizero/src/esm-examples/tmp117
    circuitUrl: https://github.com/chirimen-oh/chirimen.org/blob/master/pizero/src/esm-examples/tmp117/schematic.png
    verified: false
circuit: null
datasheet: https://www.ti.com/lit/ds/symlink/tmp117.pdf
reference: null
packages:
  - "@chirimen/tmp117"
platform: pizero-esm
status: primary
verified: false
