id: TCS34725
model: TCS34725
tag: I2C
category: 色センサ
description: I2C接続の色センサー
image: https://raw.githubusercontent.com/chirimen-oh/chirimen.org/master/partsImgs/TCS34725.jpg
productUrl: https://akizukidenshi.com/catalog/g/g108220/
examples:
  - platform: legacy-gc-i2c
    status: archive
    upstreamRepository: chirimen-oh/chirimen
    upstreamPath: gc/i2c/i2c-TCS34725
    upstreamPathUrl: https://github.com/chirimen-oh/chirimen/tree/master/gc/i2c/i2c-TCS34725
    circuitUrl: null
    verified: false
circuit: null
datasheet: null
reference: null
packages:
  - "@chirimen/tcs34725"
platform: legacy-gc-i2c
status: archive
verified: false
